### ISSUE TITLE
Ui stuff

### ISSUE THREAD

**Issue by Barrebaron** [Luorrak/Ouroboros#26]
First off the app starts on a blank page (it might be me setting it up wrong) it'd be nice if it loaded first board on the list. 
Second the whole board page is separate, it'd be nice if it was in main menu on a drop down menu style.
Last numbering images in the image viewing as well as total number for better navigation.

**Comment by Luorrak** [comment]
I fixed the blank page problem in the most recent release.

Could you expand on what yo mean by a drop down style menu?

If you mean catalog sorting I will get on this right away.
