### ISSUE TITLE
This APP does not show anything?

### ISSUE THREAD

**Issue by metalbug** [Luorrak/Ouroboros#55]
Why don't show anything?

**Comment by Luorrak** [comment]
Standard questions.

Are you running a flashed ROM? I have had some problems with those in the past and I can't really do much if this is the case.
Have you added boards using the "+" button?
What version of android?
What version of Ouroboros?
Phone make/model?
Is the application crashing or is it failing to retrieve data from 8chan?

I need some more details of the problem.

**Comment by metalbug** [comment]
yes i can add "+"  some like “ggg” there is content, but Boards It's empty inside. 
Ouroboros-V0.10.3.apk
MI3
android4.4.4

**Comment by Luorrak** [comment]
Is it all boards or just a few? Which board are you trying to add? I'll see if I can reproduce it somehow.

You might want to try uninstalling and reinstalling it if you are coming from an older version. I may have broken the database for updating at one point and failed to implement the update correctly on my end. Let me know if that fixes it.

**Comment by metalbug** [comment]
thanks man, it no all boards, open this app show is blank...

**Comment by Luorrak** [comment]
Did you do a clean install? I'll open up an emulator later today and see if I can reproduce it.

**Comment by metalbug** [comment]
yea, it clean install. After this APP open, to list all the boards? or something, but i cant see anything.
