### ISSUE TITLE
Images no longer displaying in-app

### ISSUE THREAD

**Issue by TeeRekz** [Luorrak/Ouroboros#68]
After 8chan's most recent update, images no longer load on this app nor do they display on the 2 other 8chan viewer apps available. (The site is working fine on mobile browsers though) Reading the comments on the Play Store leads me to assume that this happening across the board to everyone using these apps and is not a device/ROM-specific problem.

OnePlus 2, Android 6.0, Resurrection Remix (CM13)

**Comment by Luorrak** [comment]
I'm already aware and w0rp has made some proposed changes. The problem is I am away from my signing key for a few days and can't push an update until I retrieve my thumb drive.

**Comment by Luorrak** [comment]
Issue fixed
